---
title: "Распределения в R: задания"
output: 
  html_document:
    css: ../css/style.css
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    highlight: pygments
editor_options: 
  chunk_output_type: console
---
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Задачка про булки

Каждый день Света съедает случайное количество булочек, которое распределено по Пуассону с параметром $10$. Затраты в рублях на каждую булочку распределены нормально $N(2,1)$. Ксюша каждый день съедает биномиальное количество булочек $Bin(8, 0.5)$. Затраты Ксюши на каждую булочку распределены равномерно на отрезке $[2;20]$. 

__а)__ Сколько в среднем Света тратит на булочки за день? 

__б)__ Чему равна дисперсия дневных расходов Светы? 

__в)__ Какова вероятность того, что за один день Света потратит больше денег, чем Ксюша?


### 2. Задачка про удава

Удав Анатолий любит французские багеты. Длина французского багета равна $1$ метру. За один укус Удав Анатолий съедает кусок случайной длины, равномерно распределённый на отрезке $[0;1]$. Для того, чтобы съесть весь багет удаву потребуется случайное количество $N$ укусов. 
Найдите $E(N)$ и $Var(N)$

### 3. Задачка про спортсменов

Для 20 участников соревнований, среди которых 8 российских, в гостинице забронировано 20 номеров. Из них 12 с видом на море. Участники соревнований наугад получают ключи от номеров. Найдите вероятность того, что номера с видом на море достанутся всем российским спортсменам.

### 4. Задачка про лампочки

Таня сидит дома на самоизоляции уже третий месяц. Интернет отключили. Ей скучно. Она достала. из ящика $5$ лампочек, вкрутила их в люстру, поставила посреди комнаты стул и стала ждать, когда первая лампочка перегорит. Время работы лампочек, $T$, имеет экспоненциальное распределение с параметром $\lambda = 0.2$ минут.

__а)__ Какова вероятность того, что первая лапочка проработает больше $10$ минут? 

__б)__ Чему равен для первой лампочки $95\%$ квантиль? Как проинтерпретировать это число?

__в)__ Пусть случайная величина $X = \min(T_1, \ldots, T_5)$ - время до перегорания первой лампочки. Оцените: 

- $P(X > 10)$
- $E(X)$

__г)__ Пусть случайная величина $Y = \max(T_1, \ldots, T_5)$ - время до перегорания последней лампочки. Оцените 

- $E(Y - X)$
- $P(Y > 2 X)$ 
- $Cov(X,Y)$,
- $Var(X), Var(Y)$, какая из дисперсий больше, почему?




